ingress:
  host: demo.dataflow.zone
uiConfig:
  db_url: sqlite:///data/backend.db

jupyterhub:
  hub:
    initContainers:
      - name: git-clone-templates
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --branch=main
          - --depth=1
          - --
          - https://github.com/aditya-r02/Jupyter.git
          - /etc/jupyterhub
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: custom-templates
            mountPath: /etc/jupyterhub
    extraVolumes:
      - name: custom-templates
        emptyDir: {}

    extraVolumeMounts:
      - name: custom-templates
        mountPath: /etc/jupyterhub
    #extraConfig:
    
    image:
      name: dataflowsnapshot/dataflow-hub
      tag: "latest"
    config:
      DummyAuthenticator:
        password: DBO@123
      JupyterHub:
        #admin_access: true
        authenticator_class: dummy
    extraConfig: 
      templates: |
        c.JupyterHub.template_paths = ['/etc/jupyterhub/']
      01-dataflo-config: |
        c.JupyterHub.logo_file = '/dataflow/logo.png'
        c.JupyterHub.tornado_settings = {
          'cookie_option' : {
            'SameSite': "none"
          },
          'headers': {
            'Content-Security-Policy': "frame-ancestors * 'self' "
          }
        }
        c.Spawner.args = ["--NotebookApp.tornado_settings={'headers':{'Content-Security-Policy': 'frame-ancestors self *'}}"]

    service:
      type: ClusterIP
      annotations: {}
      ports:
        nodePort:
      extraPorts: []
      loadBalancerIP:
    baseUrl: ""
  proxy:
    service:
      type: NodePort
      labels: {}
      annotations: {}
      nodePorts:
        http: 30009
        https:
      disableHttpPort: false
      extraPorts:
        - name: ui
          port: 8000
          targetPort: 8000
        - name: superset
          port: 8088
          targetPort: 8088
      loadBalancerIP:
      loadBalancerSourceRanges: []
    # chp relates to the proxy pod, which is responsible for routing traffic based
    # on dynamic configuration sent from JupyterHub to CHP's REST API.
    chp:
      image:
        name: quay.io/jupyterhub/configurable-http-proxy
        # tag is automatically bumped to new patch versions by the
        # watch-dependencies.yaml workflow.
        #
        tag: "4.6.0" # https://github.com/jupyterhub/configurable-http-proxy/tags
  singleuser:
    storage:
      extraVolumes: 
        - name: ui-config
          configMap:
            name: ui-config
    image:
      name: dataflowsnapshot/dataflow-notebook
      tag: "latest"
    networkTools:
      image:
        name: quay.io/jupyterhub/k8s-network-tools
        tag: "3.1.0"
    defaultUrl: /proxy/8000
    extraContainers:
      - name: ui
        image: dataflowsnapshot/dataflow-ui
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: ui-config
            mountPath: /home
      - name: superset
        image: chaitanya305/superset
        imagePullPolicy: Always
        ports:
          - containerPort: 8088
        env:
          - name: ADMIN_USERNAME
            value: admin
          - name: ADMIN_EMAIL
            value: admin@superset.com
          - name: ADMIN_PASSWORD
            value: admin 
    lifecycleHooks:
      postStart:
        exec:
          command:  ["mkdir", "-p", "/home/jovyan/airflow/dags", "/home/jovyan/airflow/plugins","/home/jovyan/airflow/logs" ]
  prePuller:
     hook:
      enabled: false
      pullOnlyOnChanges: true
      # image and the configuration below relates to the hook-image-awaiter Job
      image:
        name: quay.io/jupyterhub/k8s-image-awaiter
        tag: "3.1.0"
  ingress:
    enabled: false
  cull:
    enabled: true
    users: false # --cull-users
    adminUsers: true # --cull-admin-users
    removeNamedServers: false # --remove-named-servers
    timeout: 3600 # --timeout
    every: 600 # --cull-every
    concurrency: 10 # --concurrency
    maxAge: 0 # --max-age

  debug:
    enabled: true

  global:
    safeToShowValues: false