{{- if eq .Values.cloud_provider "aws" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-jovyan
provisioner: ebs.csi.aws.com  
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  fsType: ext4
  type: gp2
  encrypted: "true"
{{- else if eq .Values.cloud_provider "gcp" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-jovyan
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" 
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-ssd 
  replication-type: none 
{{- end }}