{{- if eq .Values.environment "demo" -}}
apiVersion: v1
kind: Secret
metadata:
    name: aws-secrets
type: Opaque
stringData:
    aws_access_key_id: 
    aws_secret_access_key: 
    aws_session_token: 
{{- end -}}