{{- if and (not (empty .Values.ingress.certificate)) (not (empty .Values.ingress.key)) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: {{ .Values.ingress.host }}
    cert-manager.io/certificate-name: tls-certificate
    cert-manager.io/common-name: {{ .Values.ingress.host }}
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: dataflow-studio
    meta.helm.sh/release-namespace: dataflow-studio
  name: tls-certificate
  namespace: dataflow-studio
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.certificate }}
  tls.key: {{ .Values.ingress.key }}
{{- end }}