apiVersion: v1
kind: ConfigMap
metadata:
    name: ui-config
data:
    dataflow.cfg : |
        [database]
        database_url = {{ .Values.uiConfig.db_url }}
        echo = true
        pool_size = 5
        max_overflow = 10
        
        [server]
        debug = True
        host = 0.0.0.0
        port = 8000

        [static]
        static_files_dir=//dataflow/app/static

        [redis]
        redis_url = {{ .Values.uiConfig.redis_url }}